export const ActionTypes = {
    LOG_IN: 'LOG_IN',
    ADD_LOGGED_USER: 'ADD_LOGGED_USER',
    ADD_JEGTY_USER: 'ADD_JEGTY_USER',
    CACHE_RAW_GAME: "CACHE_RAW_GAME",
    CACHE_ROOM_GAME: "CACHE_ROOM_GAME",
    ADD_ROOM_GAME_ID: "ADD_ROOM_GAME_ID",
    ADD_FRIEND_ID: "ADD_FRIEND_ID",
    ADD_FRIEND_REQUEST_ID: "ADD_FRIEND_REQUEST_ID",
    CACHE_JEGTY_USER: "CACHE_JEGTY_USER",
    SET_PENDING: "SET_PENDING"
};

